name: "humann_functional_profiling"
description: HUManN functional profiling from metagenomic or metatranscriptomic FASTQ data
keywords:
  - humann
  - chocophlan
  - utilitymapping
  - cat
  - fastq
  - uniref
  - metaphlan
  - metagenomics
  - microbiome
  - database
  - biobakery
tools:
  - "humann":
      description: "HUMAnN: The HMP Unified Metabolic Analysis Network, version 3"
      homepage: "http://huttenhower.sph.harvard.edu/humann"
      documentation: "http://huttenhower.sph.harvard.edu/humann"
      tool_dev_url: "https://github.com/biobakery/humann"
      doi: "10.7554/eLife.65088"
      licence: ['MIT']

input:
  - val_chocophlan_db_version:
      type: string
      description: Version of the ChocoPhlan database to download.
      pattern: "{full,DEMO,ec_filtered}"
  - val_uniref_db_version:
      type: string
      description: Version of the Uniref database to download.
      pattern: "{uniref50_diamond, uniref90_diamond, uniref50_ec_filtered_diamond, uniref90_ec_filtered_diamond,DEMO_diamond}"
  - val_utility_mapping_db_version:
      type: string
      description: Version of the Utility Mapping database to download.
      pattern: "{full,DEMO}"
  - ch_fastq:
//      type: channel(file)
      description: Read set (forward and reverse reads merged if paired-end) to be used as input.
      pattern: "*.{fastq, fastq.gz, fasta, fasta.gz}"
  - ch_metaphlan_profile:
      type: channel(file)
      description: Taxonomic profile output by running MetaPhlAn.
      pattern: "*"
  - val_renorm_units:
      type: string
      description: Renormalization scheme unit for module to normalize data table to.
      options: copies per million ["cpm"] OR relative abundance ["relab"]
                // To skip renormalization, use reads per kilobase ["rpk"] units.
      pattern: "{cpm,relab,rpk}"
  - val_group_type:
      type: string
      description: Built-in grouping options to reorganize data by function or pathway.
      pattern: "{uniref90_rxn}"
                // "regroup" currently under construction, only one option
  - val_name_type:
      type: string
      description: Built-in renaming options for table features.
      options: "kegg-orthology", "ec", "metacyc-rxn", "metacyc-pwy", "pfam", "eggnog", "go", "infogo1000"
      pattern: "{kegg-orthology, ec, metacyc-rxn, metacyc-pwy, pfam, eggnog, go, infogo1000}"

output:
  - uniref_db:
        type: directory
        description: Directory containing the downloaded Uniref database files.
        pattern: "uniref"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
