name: "downloadutilitymappingdb"
description: Download the full Utility Mapping Database
keywords:
  - humann
  - utilitymapping
  - regroup_table
  - rename_table
  - metaphlan
  - metagenomics
  - microbiome
  - database
  - biobakery
tools:
  - "humann":
      description: "HUMAnN: The HMP Unified Metabolic Analysis Network, version 3"
      homepage: "http://huttenhower.sph.harvard.edu/humann"
      documentation: "http://huttenhower.sph.harvard.edu/humann"
      tool_dev_url: "https://github.com/biobakery/humann"
      doi: "10.7554/eLife.65088"
      licence: ['MIT']

input:
  - utility_mapping_db_version:
      type: string
      description: Version of the Utility Mapping database to download.
      pattern: "*.{full,DEMO}"

output:
  - utility_mapping_db:
        type: directory
        description: Directory containing the downloaded Utility Mapping database files.
        pattern: "utilitymapping"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@tiiasfreeman"
maintainers:
  - "@tiiasfreeman"
  - "@CarsonJM"
